/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/cluster-inventory-api/apis/v1alpha1"
)

// FakeAuthTokenRequests implements AuthTokenRequestInterface
type FakeAuthTokenRequests struct {
	Fake *FakeApisV1alpha1
	ns   string
}

var authtokenrequestsResource = v1alpha1.SchemeGroupVersion.WithResource("authtokenrequests")

var authtokenrequestsKind = v1alpha1.SchemeGroupVersion.WithKind("AuthTokenRequest")

// Get takes name of the authTokenRequest, and returns the corresponding authTokenRequest object, and an error if there is any.
func (c *FakeAuthTokenRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AuthTokenRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(authtokenrequestsResource, c.ns, name), &v1alpha1.AuthTokenRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthTokenRequest), err
}

// List takes label and field selectors, and returns the list of AuthTokenRequests that match those selectors.
func (c *FakeAuthTokenRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AuthTokenRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(authtokenrequestsResource, authtokenrequestsKind, c.ns, opts), &v1alpha1.AuthTokenRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AuthTokenRequestList{ListMeta: obj.(*v1alpha1.AuthTokenRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.AuthTokenRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested authTokenRequests.
func (c *FakeAuthTokenRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(authtokenrequestsResource, c.ns, opts))

}

// Create takes the representation of a authTokenRequest and creates it.  Returns the server's representation of the authTokenRequest, and an error, if there is any.
func (c *FakeAuthTokenRequests) Create(ctx context.Context, authTokenRequest *v1alpha1.AuthTokenRequest, opts v1.CreateOptions) (result *v1alpha1.AuthTokenRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(authtokenrequestsResource, c.ns, authTokenRequest), &v1alpha1.AuthTokenRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthTokenRequest), err
}

// Update takes the representation of a authTokenRequest and updates it. Returns the server's representation of the authTokenRequest, and an error, if there is any.
func (c *FakeAuthTokenRequests) Update(ctx context.Context, authTokenRequest *v1alpha1.AuthTokenRequest, opts v1.UpdateOptions) (result *v1alpha1.AuthTokenRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(authtokenrequestsResource, c.ns, authTokenRequest), &v1alpha1.AuthTokenRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthTokenRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAuthTokenRequests) UpdateStatus(ctx context.Context, authTokenRequest *v1alpha1.AuthTokenRequest, opts v1.UpdateOptions) (*v1alpha1.AuthTokenRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(authtokenrequestsResource, "status", c.ns, authTokenRequest), &v1alpha1.AuthTokenRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthTokenRequest), err
}

// Delete takes name of the authTokenRequest and deletes it. Returns an error if one occurs.
func (c *FakeAuthTokenRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(authtokenrequestsResource, c.ns, name, opts), &v1alpha1.AuthTokenRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAuthTokenRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(authtokenrequestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AuthTokenRequestList{})
	return err
}

// Patch applies the patch and returns the patched authTokenRequest.
func (c *FakeAuthTokenRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AuthTokenRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(authtokenrequestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AuthTokenRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthTokenRequest), err
}
